const CONFIG = {
  SUPABASE_URL: "PUT_YOUR_SUPABASE_URL",
  SUPABASE_KEY: "PUT_YOUR_SUPABASE_ANON_KEY",
  AD_REWARD: 0.009,
  LINK_REWARD: 0.0009,
  MIN_WITHDRAW: 0.5,
  NOWPAYMENTS_API_KEY: "PUT_YOUR_NOWPAYMENTS_KEY",
  SITE_URL: "https://yourdomain.com"
};
